### ISSUE TITLE
uninitialized constant ResourceController

### ISSUE THREAD

**Issue by conradwt** [jamesgolick/resource_controller#8]
I installed the resource_controller as a gem and added the config.gem to the environment.rb.  However, I'm getting the following error message:

]/opt/local/lib/ruby/gems/1.9.1/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:443:in `load_missing_constant'
/opt/local/lib/ruby/gems/1.9.1/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:80:in`const_missing_with_dependencies'
/opt/local/lib/ruby/gems/1.9.1/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:92:in `const_missing'
/Users/conradwt/rails.dir/examples/purchase/app/controllers/admin/purchase_orders_controller.rb:1:in`'

**Comment by conradwt** [comment]
This issue has been resolved.

**Comment by renemadsen** [comment]
What did you do to solve this issue conradwt? I'm having the same issue, so it would be nice with a solution ;-)

**Comment by renemadsen** [comment]
Found the solution my self - and it's just to place the   config.gem "resource_controller" in your environment.rb file...

**Comment by conradwt** [comment]
Yes, this is the way that I resolved the issue.  In the future, I need to remember to post my solution(s) when I resolve the issue.
